"""生成拜访追踪清单（CSV）+ 单文件 HTML 看板。

清单字段按「实地拜访 / 商务追踪」用途设计，而非单纯游戏数据展示。

召回方法论（2026-08-17 修正后）：
  漏检教训 —— 《历史模拟器：崇祯》(app 813198) 曾被漏掉。它是国内首款 AI 原生
  历史策略游戏，但 TapTap 页面标签只有「策略」，简介全文不含 "AI" 与 "大模型"
  （用「世界推演模型」表述），且因 4 月走 Steam 首发未进 ChinaJoy 研报名单，
  导致标签召回、关键词召回、研报名单召回三条路径同时失效。

  由此确立三条规则：
  1. 平台元数据不可作为判定依据。TapTap 标签与简介均由厂商/平台填写，AI 游戏
     常主动回避 "AI" 字样（国内舆论环境下 AI 是负资产）。
  2. 关键词词表必须做反向验证。新增词表后，须用已知 AI 游戏做召回率抽查，
     确认能命中再投入使用，不能假设"简介里会写"。
     实测（validate_recall.py，5 款已知 AI 游戏）：
       标签召回率 40%（2/5）· 简介召回率 80%（4/5）· 两者取并 80%（4/5）
     漏掉的那一款正是最重要的《历史模拟器：崇祯》。
  3. 证据优先级：玩家评价文本 / 第三方深度报道 > 厂商自述 > 平台标签。
     AI 游戏的真实证据在评论区和媒体报道里，不在商店页。
"""
import csv, json, io

# ============ 主数据 ============
# conf: A=已核实(公开可查的公司主体+AI机制描述) B=较可靠(权威媒体/研报单一来源) C=待核实
ROWS = [
    dict(
        game='历史模拟器：崇祯', app_id='813198', layer='L1',
        company='青干工作室', city='杭州滨江',
        founder='制作人 追青（游戏文案出身，无计算机背景；2023 年在大厂推 AI 原生管线未成，遂离职创业）；技术侧有算法工程师参与',
        team_size='最初 2 人，现不到 10 人；无美术团队',
        funding='未公开（已实现不亏钱，制作人称"商业化跑通"指未亏损）',
        ai_mech='国内首款 AI 原生历史策略游戏。玩家用自然语言撰写诏书，无固定选项、无预设事件树；AI 解析意图后调用系统数据、逻辑推演、更新上千维度数值（国库/民心/官僚忠诚/军队士气/天灾/义军/后金动向）。多模型协作分工：世界大势推演用强力模型，对话类用小尺寸模型。接入千问 3.5 / Gemini / DeepSeek。架构为大模型作"世界引擎"+ 数据库（PolarDB）作"记忆中枢"，与阿里云在 Prompt 优化与长记忆调优做过 POC 合作。专家模式采用步进式状态机+底层数据库，推演前提正确率 98.7%、Function Call 匹配率 99.86%',
        ai_cost='披露最彻底的案例。单次游玩 Token 消耗达 3000 万级；要求模型输出 80-120 token/秒（主流仅 50-60）才能把等待压到 2 分钟内；玩家成本约 1 元/小时（接近传统点卡）。首发采用 48 元买断+Token 内购，引发大量差评，Steam 好评率仅 54%（1265 条评测）；后开放自定义 API（仅约 20% 玩家使用），6/25 起因国产大模型能力提升与成本下降转为免费游玩',
        stage='2026-05-08 Steam 上线，已转免费；TapTap 评分 7.9、粉丝 3971。次日留存 75.1%，非工作日平均在线 7 小时，留存率 70-78.3%',
        channel='Steam + TapTap（app 813198，含电脑/主机版）',
        contact='TapTap 官方论坛 / Steam 社区；工作室位于杭州滨江',
        expo='未进 ChinaJoy 2026 名单（4 月即公测，走 Steam 首发路线）',
        other_product='已上线创意工坊与官方示范 MOD《罗马：塞维鲁》，框架可套用三国/武侠/修仙等题材',
        visit_value='最高，优先级应排在麦琪的花园之前。理由：一是唯一把 AI 原生做成商业产品并公开完整成本模型的团队（Token 消耗量级、吞吐要求、单位成本、定价翻车全过程都有公开数据）；二是不到 10 人无美术团队却跑出 7 小时日均时长，对你 3 人团队的《除役者》资源配置有直接参照；三是同在杭州，与乌托/谦贞数字可安排同一趟行程；四是制作人对"AI 原生"的定义最锐利——把 AI 剥离后游戏还能不能玩',
        conf='A',
        src='TapTap 详情页实时抓取（2026-08-17）/ 新华财经 2026-04-13 / IT之家 2026-05-12 / 36氪《翻车？第一款AI游戏仅剩54%好评》/ Vista天下次元制作人专访 2026-06-16 / 百度百科',
    ),
    dict(
        game='麦琪的花园 Magi Scapes', app_id='', layer='L1',
        company='深圳奥拓盖母科技有限公司 (AutoGame)', city='深圳',
        founder='张昊阳（前腾讯《和平精英》AI 负责人 / 内部AI项目《伊甸岛》制作人）',
        team_size='约 11 人（早期）',
        funding='多轮共数千万元：奇绩创坛、九合创投、璀璨资本（约10%）',
        ai_mech='全游戏逻辑架构在脚本语言上，可由AI实时生成与更新；上传图片或文字描述生成AI伙伴（含像素立绘），AI生成对话/剧情/物品/实时语音（中日英）；用RAG解决长期记忆',
        ai_cost='公开披露：用低价模型+代码替换高价模型，AI相关Token成本降约80%；将模型消耗封装为「AI伙伴招募」商品',
        stage='已三测，Steam 有 Demo，定档 Steam 新品节后移动端',
        channel='Steam + TapTap',
        contact='contact@autogame.ai / 官网 autogame.ai / B站 space.bilibili.com/1775149662',
        expo='CCG EXPO 2025、ChinaJoy 2026、深圳展 15号馆A47',
        other_product='AI游戏原生编辑器《代号:ADG》—— 自然语言在 UE5 中直接创作游戏',
        visit_value='最高。AI管线+AI玩法双线，且是极少数公开AI成本结构的团队；ADG 与你的 UE5 技术栈直接相关',
        conf='A',
        src='深圳新闻网企业名录/CCG EXPO报道/游戏艺术家专访/东吴传媒研报/企查查股权',
    ),
    dict(
        game='乌托 Agentopia', app_id='773812', layer='L1',
        company='杭州谦贞数字科技有限公司 / 乌宝工作室', city='杭州',
        founder='CEO 王金鹏（法国CNRS博士、之江实验室研究员）；产品 李玉全（哈工大+波尔多双硕士，法国IMS实验室NLP）；技术 贾新宇（前《天天狼人杀》负责人，前阿里云/百度云架构师）',
        team_size='9 人起步',
        funding='已完成第三轮融资',
        ai_mech='自研 JPAF 人格模拟算法（基于荣格八维认知理论），已在 arXiv 开源，为全球AI+分析心理学结合的首发研究之一；角色经历事件后会改变人格类型；深度角色定制+智能剧情生成',
        ai_cost='未公开',
        stage='2026-03-19 起 TapTap 不限量测试；TapTap 新品榜第2、预约榜第5',
        channel='TapTap（安卓+iOS）',
        contact='TapTap 官方入驻页 / 玩家QQ群 671492232',
        expo='待核实',
        other_product='早期复现过 Character.AI 形态与斯坦福小镇（2D/3D多形态）',
        visit_value='高。算法驱动型团队，6项AI发明专利，有可公开引用的学术产出；同在长三角，拜访成本低',
        conf='A',
        src='TapTap官方详情页/腾讯新闻深度专访/游戏矩阵报道',
    ),
    dict(
        game='福尔摩斯：暗夜追踪者', app_id='', layer='L1',
        company='上海美酷瑞 (MacRoy)', city='上海',
        founder='朱笑靖（前盛大游戏VP）、吴昀贇（前B站游戏事业部负责人）；二人曾共创分众游戏、元境界科技',
        team_size='待核实',
        funding='待核实（2024-07 成立）',
        ai_mech='数十个AI扮演NPC，游戏内无任何剧情选项；AI逻辑判定系统综合对话逻辑/情绪识别/行为分析动态判定任务完成度；自研情绪表演系统（面部100+骨骼、8种基础情绪）；自研实时语音引擎毫秒级响应+唇形同步',
        ai_cost='未公开',
        stage='Steam + TapTap 已开启预约；2025-01 登记软著',
        channel='Steam + TapTap',
        contact='待核实',
        expo='待核实',
        other_product='首款产品，公司主攻AI前沿技术创新游戏',
        visit_value='高。团队履历最重（盛大VP+B站游戏负责人），主导过《FGO》《碧蓝航线》《热血传奇手游版》发行；3D大型AI推理游戏是重资产路线，与《除役者》的UE5 ARPG 定位可对标',
        conf='B',
        src='字符无限科技/头条报道 2025-05',
    ),
    dict(
        game='群星低语 Whispers from the Star', app_id='746715', layer='L1',
        company='Anuttacon（蔡浩宇 AI 创业公司）', city='美国/新加坡（非国内，实地拜访不可行）',
        founder='蔡浩宇（米哈游创始人、原CEO）',
        team_size='待核实',
        funding='待核实',
        ai_mech='实时文字、语音、视频通话驱动剧情；玩家话语决定角色斯特拉命运；开放式对话为核心，无固定选项',
        ai_cost='未公开',
        stage='2025-03-15 海外开启测试招募；TapTap 预约 6.8 万、粉丝 6.8 万、评分 8.0',
        channel='TapTap 预约页（海外为主）',
        contact='待核实',
        expo='待核实',
        other_product='—',
        visit_value='仅作标杆参考，团队在海外，实地拜访不可行；但是多模态实时交互AI游戏的行业风向标',
        conf='A',
        src='TapTap官方详情页实时抓取（2026-08-17）+ 研报',
    ),
    dict(
        game='超自然行动组', app_id='', layer='L2',
        company='巨人网络', city='上海',
        founder='—（上市公司）',
        team_size='—',
        funding='上市公司',
        ai_mech='内置AI驱动「AI假人」，接入通义千问模型；能理解玩家语义、复刻真人音色、模拟玩家语言风格与行动逻辑，做出具策略性和迷惑性的伪装动作；上线首周 AI NPC 与真人对局超 2500 万次',
        ai_cost='未公开',
        stage='已上线运营一年+，DAU破千万、累计注册2亿、流水超50亿；TapTap 评分 7.0',
        channel='全渠道 + TapTap',
        contact='巨人网络公开渠道（上海松江）',
        expo='ChinaJoy 常设展台',
        other_product='前CEO吴萌已离职投入AI游戏创业并获融资',
        visit_value='高。国内唯一已验证「AI NPC带动大DAU商业成功」的案例，AI假人是可规模化的范式；同在上海',
        conf='A',
        src='腾讯新闻《中国游戏进入与AI同游时代》2026-08',
    ),
    dict(
        game='不问凡尘', app_id='', layer='L1',
        company='字节跳动 江南工作室', city='上海 / 杭州（待核实具体办公地）',
        founder='—（大厂内部工作室）',
        team_size='—',
        funding='大厂自有',
        ai_mech='基于 Seedance 模型的 AI 真人 RPG；玩家每个选择以非剧情方式累积，影响数值与世界反馈；内置 AI 驱动 NPC 说服玩法',
        ai_cost='未公开',
        stage='ChinaJoy 2026 展出',
        channel='待核实',
        contact='待核实',
        expo='ChinaJoy 2026',
        other_product='Seedance 视频模型（TapTap 制造亦将接入）',
        visit_value='中高。大厂拜访门槛高，但 Seedance 驱动的真人RPG 是视频模型入游的最前沿样本',
        conf='B',
        src='东吴传媒 ChinaJoy 2026 点评报告',
    ),
    dict(
        game='印格 Engram', app_id='', layer='L1',
        company='上海柚衣科技', city='上海',
        founder='待核实',
        team_size='待核实',
        funding='待核实',
        ai_mech='AI驱动 CRPG；玩家与基于AI的NPC对话，NPC根据玩家行动与语言做出不同反应并影响后续剧情',
        ai_cost='未公开',
        stage='完整度低于《麦琪的花园》，计划 Steam 试玩版',
        channel='Steam（TapTap 待核实）',
        contact='待核实',
        expo='CCG EXPO 2025',
        other_product='—',
        visit_value='中高。同在上海，早期团队易接触，CRPG+AI 是叙事重度方向',
        conf='B',
        src='CCG EXPO 2025 报道（OFweek）',
    ),
    dict(
        game='AIFriends', app_id='771203', layer='L1',
        company='上海惊喜先生科技有限公司', city='上海',
        founder='待核实',
        team_size='待核实',
        funding='待核实',
        ai_mech='AI伙伴养成；UGC版本支持通过SDK上传角色模型、设定人格与故事、选择或克隆音色、亲密度养成、角色广场共享',
        ai_cost='未公开',
        stage='2025-08-30 上线；TapTap 评分 7.4、关注 12.1 万',
        channel='TapTap',
        contact='TapTap 官方入驻页',
        expo='待核实',
        other_product='—',
        visit_value='中。AI陪伴+UGC结合，音色克隆与3D模型上传管线值得看；同在上海',
        conf='A',
        src='TapTap官方详情页实时抓取（2026-08-17）',
    ),
    dict(
        game='EVE', app_id='', layer='L1',
        company='自然选择（深圳）智能有限公司', city='深圳',
        founder='待核实（团队含多位女性成员，本身为目标用户）',
        team_size='待核实',
        funding='待核实',
        ai_mech='AI伴侣；支持3D实时通话并可开启摄像头让AI「看见」现实世界；好感度提升解锁剧情；陪伴/家园/朋友圈/送礼系统',
        ai_cost='未公开',
        stage='2026-04-10 上线，已完成两轮测试；仅面向中国地区',
        channel='iOS + TapTap',
        contact='待核实',
        expo='待核实',
        other_product='—',
        visit_value='中。多模态视觉输入的陪伴产品，摄像头实时理解是差异点',
        conf='B',
        src='媒体报道 sounova',
    ),
    dict(
        game='AI小镇：星原（Aivilization）', app_id='', layer='L1',
        company='紫荆智能（香港科技大学孵化）', city='待核实',
        founder='2023 年成立，早期做政企 AI 服务', team_size='待核实', funding='待核实',
        ai_mech='多智能体驱动的自主生活模拟，被称作「AI 版星露谷」。小镇由 Agent 自主运转：角色有记忆、性格和生活目标，自主种地打工社交，玩家离线时世界仍持续演进；玩家用自然语言下指令养成角色；支持一句话生成可交互小剧场（AI 实时生成场景、物品、行为）与全玩家共创世界',
        ai_cost='未公开',
        stage='2024-08 以 Aivilization 之名上线测试（玩家超 10 万），后关闭约四个月，2025 年底更名「AI小镇：星原」重新开放，当前官网预约阶段',
        channel='网页端（无 TapTap/Steam 页面）', contact='官网 aivilization.ai / aitown.com.cn',
        expo='ChinaJoy 2026',
        other_product='—',
        visit_value='中高。港科大孵化的多智能体团队，「离线时世界持续演进」是差异化设计；网页端形态与你项目形态不同但 Agent 调度经验可借鉴',
        conf='B', src='东吴传媒 ChinaJoy 2026 点评报告 + 团队报道（头条 7669749637653266996）',
    ),
    dict(
        game='遥远行星：建造师', app_id='756378', layer='L1',
        company='哇工作室 wastudio / 广州阁道科技有限公司', city='广州',
        founder='制作人 刘寒（前腾讯极光计划发行，经手《隐形守护者》《我的侠客》）',
        team_size='十余人', funding='待核实',
        ai_mech='AI 放进系统内部而非只做对话：荧河星系 150+ 星球、600+ NPC 全部由 AI 驱动，有独立背景、记忆、目标和立场，会自主交易、结盟、报复；经济系统由 AI 行为实时驱动，物价随战争、灾害、供需波动形成蝴蝶效应；另有 Roguelike 虫洞开拓与 AI 助手「索菲亚」多周目叙事。AI 底层由超参数科技 Knit 智能体平台支撑，可换模型接口',
        ai_cost='未公开',
        stage='2026-05-26 Steam 抢先体验上线（买断制，有 Demo，WeGame 同步）；TapTap PC 页评分 8.4，另有移动页（737953，未见移动端上线）',
        channel='Steam + WeGame + TapTap', contact='TapTap 官方页 / Steam 社区',
        expo='待核实',
        other_product='超参数科技 Knit 智能体平台（knit.top，技术供应商）',
        visit_value='高。「AI 驱动整个经济系统」是你 RTS+塔防最该看的系统级用例；制作人有大厂发行背景好沟通；广州',
        conf='A', src='TapTap 详情页实测（2026-08-18）+ Steam EA 页 + gdgame.org 资料页',
    ),
    dict(
        game='AI2U：与你直到世界尽头', app_id='765584', layer='L1',
        company='AlterStaff Inc.（发行 Neverland Entertainment）', city='跨中美远程',
        founder='创始人 大谷 Spitzer（B 站「大谷的游戏创作小屋」UP 主）',
        team_size='约 16 人', funding='待核实',
        ai_mech='「第一款密室逃脱 AI 游戏」：玩家被病娇 AI 女友（猫娘/魔女/全息 AI/人鱼）困在各自空间，靠自由自然语言对话+场景物品交互说服放行；LLM 云端实时生成对话，无预设对话树；话术影响好感度、NPC 情绪与每局结局（多结局）；前身是 2023 年 itch.io 爆款 Demo《AI 病娇猫娘模拟器》',
        ai_cost='未公开',
        stage='2026-08 结束抢先体验上线 Steam 1.0 正式版（Win/Mac，国区约 66 元，好评率约 89%）',
        channel='Steam + TapTap', contact='TapTap 官方页 / B 站大谷的游戏创作小屋',
        expo='待核实', other_product='—',
        visit_value='中高。已跑通商业闭环（1.0 正式版+89% 好评）的少数人团队；「无对话树纯自由对话说服 NPC」的提示词与护栏设计值得拆',
        conf='A', src='TapTap 详情页实测（2026-08-18）+ Steam 页',
    ),
    dict(
        game='Bside（Bside: Desktop Mate）', app_id='', layer='L1',
        company='Kotoko 工作室（Kotoko Inc. / BIIBIT）', city='待核实',
        founder='创始人 乔海鑫（97 年生，前真格基金、Yahaha Studios 创始成员）；班底来自腾讯、网易、米哈游、叠纸',
        team_size='十余人', funding='种子轮（红杉）',
        ai_mech='OC 养成+AI 驱动的多人社交桌面陪伴：玩家创建原创角色 Biibit（外观人设+提示词），由大模型驱动在桌面上自主生活、基于人设与环境互动、交朋友、发「仅你可见」的朋友圈；玩家可创建咖啡馆/魔法小镇等自主运行的小世界，Biibit 无脚本生活并形成记忆；可与其他玩家的 Biibit 社交��页面标注接入 Claude',
        ai_cost='未公开',
        stage='2025-10-28 Steam 抢先体验免费上线（Win/Mac/Linux，含内购）；另有「Bside 中文版」Steam 页即将推出',
        channel='Steam + 官网 bside.zone', contact='官网 bside.zone',
        expo='待核实', other_product='—',
        visit_value='中高。红杉种子的 OC+Agent 团队，与乌托同赛道但路线偏桌面挂机社交；班底履历强',
        conf='A', src='Steam 页 + 网易研报引用官网',
    ),
    dict(
        game='星夜颂歌', app_id='', layer='L1',
        company='奇点摄动 SingularDance', city='待核实',
        founder='创始人 Edward（帝国理工计算机）；AI 科学家 Ken（清华/牛津双博士，曾主导 NASA 项目）；制作人 Justice（前 EVE Online 制作人）',
        team_size='待核实', funding='千万级天使+轮（九合创投领投）',
        ai_mech='AI 二次元「赛博生命」桌面陪伴：来自公元 7000 年的少女蕾伊以动画级 3D 形象生活在桌面天台场景；自研 GEM 超人格化模型（性格价值观内化进模型权重而非 prompt 堆砌）；「星空记忆」按角色主观情感组织记忆；自主生活流（养电子金鱼、刷 B 站小红书、主动发起对话、生气转身离开）；「广播式」算力分发架构降成本；交互中对话仅占约 1/3',
        ai_cost='未公开（广播式算力分发架构为降本设计）',
        stage='2026-02 首次特邀预览测试（小规模），当前预约内测阶段；Windows PC 桌面应用（推荐 RTX 3060），计划延伸移动端与 IoT',
        channel='官方渠道预约（c.aiiz.cn/xRYbWs），无 TapTap/Steam 页', contact='官方预约链接 / B 站官方号',
        expo='待核实', other_product='—',
        visit_value='高。人格写进模型权重（非 prompt）+ 对话仅占 1/3 的产品观，是陪伴品类里技术最激进的路线；创始团队学术与 3A 履历兼具',
        conf='B', src='DoNews 报道（donews 6454247）+ B 站官方视频',
    ),
    dict(
        game='芽灵小屋', app_id='860204', layer='L1',
        company='行者工作室 / 上海行者互娱科技有限公司', city='上海',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='「记忆养成」AI 小人模拟：玩家通过心愿召唤 AI 小人「芽灵」住进小屋，自由捏人（外貌性格背景）；芽灵自主生活（吃饭工作锻炼、流露小情绪）并写日记记录心理活动；所有聊天、布置家具、安排日程都会成为长期记忆，随累积形成独特偏好、性格和与玩家的关系',
        ai_cost='未公开',
        stage='预约中（TapTap 手游，Steam 页已开发行日期待宣布，含单人与联机标签）',
        channel='Steam + TapTap', contact='TapTap 官方页',
        expo='待核实', other_product='—',
        visit_value='中。上海团队好约；「记忆驱动性格分化」机制清晰，但轻量玩法体量上限不高',
        conf='A', src='TapTap 详情页实测（2026-08-18）+ Steam 页',
    ),
    dict(
        game='灵壳计划 EchoShell', app_id='', layer='L1',
        company='Microfeel / 微直觉', city='南京江宁 + 上海徐汇',
        founder='待核实（在招世界模型、Agent 蒸馏等研究岗）', team_size='待核实', funding='待核实',
        ai_mech='AI Sandbox / AI World：玩家放置元素即触发 AI 实时生成场景与剧情，无需建模或编程；与 NPC 自由对话可实时改变世界，且 NPC 由真实玩家创建；世界状态持续演化、角色有长期记忆与自主行为逻辑、玩家行为对世界产生长期影响；AI 生成内容经 OpenAI 审核模型过滤',
        ai_cost='未公开',
        stage='Steam 页 Coming soon（原计划 2026-06，未如期，仅 PC/Windows）',
        channel='Steam', contact='待核实',
        expo='待核实', other_product='—',
        visit_value='中高。AI World 路线与你的 RTS 世界构建有技术交集；南京+上海双办公点可约；但发售延期需关注团队状态',
        conf='B', src='Steam 页 + 招聘信息',
    ),
    dict(
        game='诡秘推理', app_id='', layer='L1',
        company='BC 工作室（Battlecry Studio）', city='待核实',
        founder='独立团队', team_size='待核实', funding='待核实',
        ai_mech='AI 驱动自由对话的新本格推理：玩家扮演异常事务调查局探员勘查命案，可拿任何证物向任何人自由提问；NPC 接入 LLM，基于性格、立场与所守秘密实时生成回答，甚至会做伪证；对话可击破嫌疑人心理防线或提升好感解锁隐藏剧情；用类模型微调+Prompt 范例构建知识库，保证 NPC 在约 40 万字剧情中行为一致；4 个核心案件、3 主线结局+20 余支线结局',
        ai_cost='未公开',
        stage='Steam 正式版 2025-11 上线（49 元），此前有免费 Demo；获 2025 腾讯游戏创作大赛 AI 玩法创作奖+PC 游戏创新奖',
        channel='Steam + TapTap 论坛', contact='TapTap 官方动态 / 机核',
        expo='待核实', other_product='—',
        visit_value='中高。「NPC 做伪证」+40 万字一致性控制是叙事类 AI 游戏最难的工程问题，与福尔摩斯：暗夜追踪者同题竞技，可对比',
        conf='B', src='Steam 页 + 腾讯游戏创作大赛获奖记录',
    ),
    dict(
        game='妹居物语', app_id='782330', layer='L1',
        company='独立开发者 彩奈（一人团队）', city='待核实',
        founder='前游戏公司策划，自学 AI 两个月做出首版',
        team_size='1 人', funding='无',
        ai_mech='AI 情感陪伴生活模拟：与 AI 妹妹 Yuki 同居，文字/语音实时自由对话；长期记忆系统（向量检索+时间衰减+重要性评估，本地数据库召回）；AI 日记；好感/信任数值驱动傲娇、病娇人格转变，病娇状态会扫描玩家硬盘生成「打破第四面墙」对话；约会、五子棋、AI 跑团讲故事、桌宠等模块；数值加减由 AI 自行判断',
        ai_cost='未公开',
        stage='Demo 已上线 Steam 与 TapTap（TapTap 评分 9.6、手游+PC 双平台）；Steam 正式版计划 2026 年发售，作者正接触发行商',
        channel='Steam + TapTap', contact='TapTap 官方页',
        expo='待核实', other_product='—',
        visit_value='中。一人团队+9.6 分的极端案例，说明单人+AI 管线能做出什么；拜访成本极低（线上即可）',
        conf='B', src='TapTap 详情页实测（2026-08-18）+ 游戏葡萄专访（163 KCALPHKD05268BP2）',
    ),
    dict(
        game='千夜之书 1001（1001 Nights）', app_id='', layer='L1',
        company='Ada Eden', city='伦敦（成员分布中国/英国/北美）',
        founder='创始人 孙羽茜（清华本科、皇家艺术学院博士，现居伦敦）',
        team_size='约 10 人', funding='待核实',
        ai_mech='AI 原生互动叙事+轻 Roguelike：玩家扮演山鲁佐德给 AI 驱动的国王讲故事续命，诱导国王说出「剑」「刀」等词使其具象化为独一无二的武器卡牌（GLM/GPT 实时生成）；集齐武器进入战斗，战斗台词与效果也源自玩家创作的故事；每局生成专属故事书；美术全部由人类画师创作；项目发表过两篇学术论文，获 IndiePlay、A MAZE 提名',
        ai_cost='未公开',
        stage='Steam 免费 Demo 已上线，正式版即将宣布；另有 itch.io 试玩与官网 1001nights.ai',
        channel='Steam + itch.io + 官网', contact='官网 1001nights.ai',
        expo='IndiePlay / A MAZE 提名',
        other_product='—',
        visit_value='中高。学术型团队（皇艺博士+两篇论文），「诱导 AI 说词生成武器」的玩法设计极有原创性；但团队在海外，实地拜访需线上',
        conf='A', src='Steam 页 + 触乐报道（qq LNK2024111500671100）+ 官网',
    ),
    dict(
        game='共鸣计划（Project RESONANCE）', app_id='', layer='L1',
        company='灵榫游戏（Ling Sun Game）', city='待核实',
        founder='2024 年成立，核心成员来自国内头部游戏与 AI 企业',
        team_size='待核实', funding='待核实',
        ai_mech='AI 原生少女乐队养成：玩家扮演经纪人，通过提示词交互生成性格各异的乐队成员；角色原画、立绘、表情、剧情事件均由 AI 实时生成；AI 角色记忆玩家对话、自主安排团队活动，无人干预时也会自主生活；玩家与 AI 共同创作的歌曲（旋律、编曲、人声）实时生成并写入专辑；关键羁绊时刻凝结为独一无二的「灵感瞬间」插画；有运行时内容过滤',
        ai_cost='未公开',
        stage='Steam 页已上线，计划 2026 年发售；ChinaJoy 2026 提供现场试玩',
        channel='Steam', contact='待核实',
        expo='ChinaJoy 2026', other_product='—',
        visit_value='中高。美术+剧情+音乐全栈 AI 实时生成，是 L1 里生成维度最全的；头部企业背景团队',
        conf='B', src='Steam 页 + ChinaJoy 2026 试玩 + 游民星空资料页',
    ),
    dict(
        game='雾岛新闻社', app_id='', layer='L1',
        company='我摸了 / Imgooed 制作组（主创 aquqa）', city='待核实',
        founder='为爱发电型独立团队，曾通过机核招募成员',
        team_size='小团队', funding='无',
        ai_mech='AI 原生「零打字」新闻社经营 AVG：玩家扮演新闻社社长，通过点击、拖拽线索（而非键盘输入）完成调查采访、编辑新闻稿（可选倒金字塔体、华尔街日报体等文体）、发布报道，用舆论改写世界走向；文本与选项由 LLM 实时生成；美术为人类画师绘制；需联网并配置 API 密钥游玩',
        ai_cost='玩家自备 API Key（BYOK 模式）',
        stage='Demo 已在 itch.io 上线（Windows，QQ 群提供公用 Key）；未见 Steam/TapTap 页',
        channel='itch.io（aquqa.itch.io/kirishima-news-club）', contact='机核 aquqa 主页 / 爱发电 afdian.com/a/aquqa',
        expo='待核实', other_product='—',
        visit_value='中。「零打字」是对 AI 对话游戏输入门槛的巧妙解法；BYOK 模式把成本完全转嫁玩家，商业模式与你的 Token 成本顾虑直接相关',
        conf='B', src='itch.io + 机核主创主页',
    ),
    dict(
        game='代号：如意（如意情探）', app_id='', layer='L1',
        company='CyberPinky 工作室（NVIDIA Inception 成员企业）', city='待核实',
        founder='创始人 张志会', team_size='待核实', funding='待核实',
        ai_mech='AI 驱动 3D 互动陪伴乙女手游：玩家在「现实—如意」两界交界与官方原创男主完成主线与日常互动；高度自由的 AI 开放对话不受固定剧本限制；角色有独立个性、情绪与行为逻辑，按玩家语气、互动频率实时反应；多层次记忆系统与精准召回（缓解 OOC 与失忆）；实时语音、视觉识别、3D 实时面对面交互',
        ai_cost='未公开',
        stage='2025-11-03 启动滚动内测；移动端（iOS/安卓），未查到 TapTap/Steam 商店页',
        channel='官方渠道（cyberpinky.co）', contact='官网 cyberpinky.co',
        expo='待核实', other_product='—',
        visit_value='中。NVIDIA Inception 成员身份说明有技术背书；3D 实时面对面+视觉识别在乙女品类少见',
        conf='B', src='CyberPinky 官网 + 内测报道（sounova）',
    ),
    dict(
        game='Lunaverse（Lunaverse Stories）', app_id='', layer='L1',
        company='MobAI', city='待核实',
        founder='CEO 钟文鼎 Vito（前头部 VC）；CPO 王博 Kaito（前国内头部 AI UGC 平台早期核心成员）；CTO 张奥多 August（中科大 AI 博士）',
        team_size='4 人（00 后团队）', funding='赤子城科技（HK.09911）数百万元天使轮独家投资',
        ai_mech='AI 互动叙事游戏平台（主攻北美 18-24 岁女性）：互动游戏 Feed 流，玩法灵感来自跑团掷骰；「Remix Anywhere」允许玩家在任意剧情节点插入想法，AI 实时生成专属支线；「Dream Universe」后台追踪玩家选择偏好，生成个性化支线并分发给偏好相近的用户；配套创作者工具 Lunaverse IDE（AI 辅助编剧、资产一键生成、自动化发布）',
        ai_cost='未公开',
        stage='2026-07/08 内测，正式上线计划 2027-Q2；移动 App（iOS/安卓，面向海外）',
        channel='海外移动 App（无 TapTap/Steam 页）', contact='待核实',
        expo='待核实', other_product='Lunaverse IDE（创作者工具）',
        visit_value='中。平台型路线而非单品，与你做产品的定位不同；但「支线生成后分发给偏好相近用户」的内容复用思路值得关注',
        conf='B', src='36氪首发（hstong 转载）+ 速途网融资报道',
    ),

    dict(
        game='混想局', app_id='', layer='L1',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='玩家自由输入或词条组合，AI 即时生成角色、技能与流派，随机事件中组建战队（AI Roguelike 构筑）',
        ai_cost='未公开', stage='ChinaJoy 2026 展出',
        channel='待核实', contact='待核实', expo='ChinaJoy 2026', other_product='—',
        visit_value='中。AI实时生成技能与流派，与你的RTS+塔防构筑思路有交叉参考价值',
        conf='C', src='东吴传媒 ChinaJoy 2026 点评报告',
    ),
    dict(
        game='黑箱：无限构筑', app_id='', layer='L1',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='数百种底层原子项动态重组生成独特技能（AI Roguelike 构筑）',
        ai_cost='未公开', stage='ChinaJoy 2026 展出',
        channel='待核实', contact='待核实', expo='ChinaJoy 2026', other_product='—',
        visit_value='中。原子项重组机制对塔防/RTS技能系统设计有直接借鉴',
        conf='C', src='东吴传媒 ChinaJoy 2026 点评报告',
    ),
    dict(
        game='MoMo', app_id='', layer='L1',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='实时同步玩家所在城市天气与活动信息，提供与 AI NPC 玩游戏、办公、看电影等体验；丰富上下文构建陪伴感',
        ai_cost='未公开', stage='ChinaJoy 2026 展出',
        channel='待核实', contact='待核实', expo='ChinaJoy 2026', other_product='—',
        visit_value='中低。现实世界上下文接入是亮点，但属陪伴品类，与你主线关联弱',
        conf='C', src='东吴传媒 ChinaJoy 2026 点评报告',
    ),
    dict(
        game='假如我是人工智能 If I am AI', app_id='156070', layer='L1',
        company='内购人生PABL', city='待核实',
        founder='待核实', team_size='个人/小团队', funding='无',
        ai_mech='AI 主题文字点击类；官方 ai 标签收录（需实测确认是否为运行时接入模型，或仅AI题材）',
        ai_cost='未公开',
        stage='已上线；TapTap 评分 9.5、预约 8827、粉丝 9151',
        channel='TapTap', contact='TapTap 官方页', expo='—', other_product='—',
        visit_value='低。评分高但体量小，且存在「AI题材而非AI技术」的可能，需先实测再决定是否拜访',
        conf='C', src='TapTap官方详情页实时抓取（2026-08-17）',
    ),
    dict(
        game='星眠', app_id='', layer='L1',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='AI 陪伴乙女；AI 动态陪伴系统实时生成对话（非固定台词），Live2D 触摸互动 + 模拟经营 + 快穿剧情',
        ai_cost='未公开', stage='2026-07-21 开启预约',
        channel='官网 + TapTap', contact='待核实', expo='待核实', other_product='—',
        visit_value='中低。乙女+AI 细分赛道，Live2D与实时对话结合的工程实现可参考',
        conf='C', src='媒体报道 sounova',
    ),
    dict(
        game='赎命电波', app_id='', layer='L1',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='接入AI赋予NPC自由交互，或玩家与AI对话共同续写故事',
        ai_cost='未公开', stage='待核实',
        channel='待核实', contact='待核实', expo='待核实', other_product='—',
        visit_value='中低。信息过少，需先补齐主体', conf='C',
        src='东吴传媒 ChinaJoy 2026 点评报告',
    ),
    dict(
        game='重生之我在产业园当AI', app_id='', layer='L1',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='AI对话驱动叙事，玩家在设定世界观下与AI共同续写故事',
        ai_cost='未公开', stage='待核实',
        channel='待核实', contact='待核实', expo='待核实', other_product='—',
        visit_value='中低。信息过少，需先补齐主体', conf='C',
        src='东吴传媒 ChinaJoy 2026 点评报告',
    ),
    dict(
        game='流言侦探', app_id='', layer='L2',
        company='待核实', city='待核实',
        founder='待核实', team_size='待核实', funding='待核实',
        ai_mech='模拟AI社交与真人聊天体验，多线结局；需实测确认是否运行时接入模型',
        ai_cost='未公开',
        stage='已上线，番外《白樱抄》已更新；评分 9.2、编辑推荐',
        channel='TapTap', contact='待核实', expo='待核实', other_product='—',
        visit_value='中低。口碑极好但AI成分待核实，可能是脚本模拟而非真AI', conf='C',
        src='TapTap 首页推荐位',
    ),
]

EXCLUDED = [
    dict(game='异常', app_id='59622', company='Kunpo', score='9.6',
         reason='带 ai 标签但实际是黑客/编程/解谜主题，无运行时AI或AI管线证据 —— 官方标签误伤的典型'),
    dict(game='TapTap 制造全部产出（约 4000+ 款）', app_id='810249', company='心动/TapTap 平台',
         score='—', reason='按需求明确排除。含《AI文字冒险》等由 TapTap 制造创作者发布的作品'),
    dict(game='晚安不忧屋', app_id='', company='恺英网络 SOON 平台', score='—',
         reason='属于其他AI创作平台的产出，非独立团队自研管线，与Maker性质相同'),
]

FIELDS = [
    ('game', '游戏名'), ('platform', '平台'), ('layer', 'AI介入层级'), ('conf', '置信度'),
    ('company', '公司主体'), ('city', '所在城市'), ('founder', '核心团队背景'),
    ('team_size', '团队规模'), ('funding', '融资情况'),
    ('ai_mech', 'AI机制描述'), ('ai_cost', 'AI成本披露'),
    ('stage', '当前阶段与数据'), ('channel', '发行渠道'),
    ('contact', '联系方式'), ('expo', '展会出没记录'),
    ('other_product', '其他产品/工具链'), ('visit_value', '拜访价值判断'),
    ('app_id', 'TapTap AppID'), ('links', '相关链接'), ('src', '证据来源'),
]

# 相关链接（商店页/官网/报道）。全部来自调研时实际检索到的 URL，未做猜测。
LINKS = {
    '历史模拟器：崇祯': ['https://www.taptap.cn/app/813198'],
    '麦琪的花园 Magi Scapes': ['https://store.steampowered.com/app/2990190/', 'https://autogame.ai'],
    '乌托 Agentopia': ['https://www.taptap.cn/app/773812'],
    '群星低语 Whispers from the Star': ['https://www.taptap.cn/app/746715'],
    'AIFriends': ['https://www.taptap.cn/app/771203'],
    '假如我是人工智能 If I am AI': ['https://www.taptap.cn/app/156070'],
    'AI小镇：星原（Aivilization）': ['https://aivilization.ai/', 'https://aitown.com.cn'],
    '遥远行星：建造师': ['https://store.steampowered.com/app/3105960/', 'https://www.taptap.cn/app/756378', 'https://wegamedb.info/products/2008511'],
    'AI2U：与你直到世界尽头': ['https://store.steampowered.com/app/2880730/', 'https://www.taptap.cn/app/765584/all-info'],
    'Bside（Bside: Desktop Mate）': ['https://store.steampowered.com/app/3649950/Bside_Desktop_Mate/', 'https://www.bside.zone/'],
    '星夜颂歌': ['https://c.aiiz.cn/xRYbWs', 'https://www.donews.com/news/detail/4/6454247.html'],
    '芽灵小屋': ['https://store.steampowered.com/app/3872860/_/', 'https://www.taptap.cn/app/860204'],
    '灵壳计划 EchoShell': ['https://store.steampowered.com/app/3871060'],
    '诡秘推理': ['https://store.steampowered.com/app/3184990/_/', 'https://www.taptap.cn/topic/47698476'],
    '妹居物语': ['https://store.steampowered.com/app/3963620', 'https://www.taptap.cn/app/782330'],
    '千夜之书 1001（1001 Nights）': ['https://store.steampowered.com/app/2542850/1001_Nights/', 'https://www.1001nights.ai', 'https://ada-eden.itch.io/1001-nights-official'],
    '共鸣计划（Project RESONANCE）': ['https://store.steampowered.com/app/4810230/_/'],
    '雾岛新闻社': ['https://aquqa.itch.io/kirishima-news-club', 'https://afdian.com/a/aquqa'],
    '代号：如意（如意情探）': ['https://www.cyberpinky.co/主页/'],
    'Lunaverse（Lunaverse Stories）': ['https://www.hstong.com/news/hk/detail/26070109050153127'],
    '超自然行动组': [],
    '福尔摩斯：暗夜追踪者': [],
    '不问凡尘': [],
    '印格 Engram': [],
    'EVE': [],
    '混想局': [],
    '黑箱：无限构筑': [],
    'MoMo': [],
    '星眠': [],
    '赎命电波': [],
    '重生之我在产业园当AI': [],
    '流言侦探': [],
}

# 平台标注。来源分级：「实测」= TapTap platform_info 字段抓取（2026-08-17）；
# 「渠道」= 按已知发行渠道推断；「待核实」= 信息不足。
PLATFORM = {
    '历史模拟器：崇祯': 'PC（实测；TapTap PC 端 + Steam）',
    '麦琪的花园 Magi Scapes': 'PC 优先（Steam 三测），移动端计划',
    '乌托 Agentopia': '手游双端（实测 android+iOS）',
    '福尔摩斯：暗夜追踪者': 'PC+手游（Steam + TapTap 预约）',
    '群星低语 Whispers from the Star': '手游双端（实测 android+iOS）',
    '超自然行动组': '手游+PC（全渠道，双端互通）',
    '不问凡尘': '待核实（大概率手游）',
    '印格 Engram': 'PC（Steam）',
    'AIFriends': '手游双端（实测 android+iOS）',
    'EVE': '手游（iOS + TapTap）',
    'AI小镇：星原（Aivilization）': '网页端（无商店页）',
    '遥远行星：建造师': 'PC（实测 TapTap PC 页）+ 手游页存在',
    'AI2U：与你直到世界尽头': 'PC（Steam Win/Mac）+ TapTap 页',
    'Bside（Bside: Desktop Mate）': 'PC（Steam Win/Mac/Linux）',
    '星夜颂歌': 'PC 桌面应用（计划移动端+IoT）',
    '芽灵小屋': '手游（实测 TapTap）+ PC（Steam 页已开）',
    '灵壳计划 EchoShell': 'PC（Steam，仅 Windows）',
    '诡秘推理': 'PC（Steam）',
    '妹居物语': '手游+PC（实测 TapTap 双平台 + Steam）',
    '千夜之书 1001（1001 Nights）': 'PC（Steam + itch.io）',
    '共鸣计划（Project RESONANCE）': 'PC（Steam）',
    '雾岛新闻社': 'PC（itch.io，仅 Windows）',
    '代号：如意（如意情探）': '手游（iOS/安卓，内测）',
    'Lunaverse（Lunaverse Stories）': '手游（海外 App，内测）',
    '混想局': '待核实',
    '黑箱：无限构筑': '待核实',
    'MoMo': '待核实（陪伴类大概率手游）',
    '假如我是人工智能 If I am AI': '手游双端（实测 android+iOS）',
    '星眠': '手游（预约中）',
    '赎命电波': '待核实',
    '重生之我在产业园当AI': '待核实',
    '流言侦探': '手游（TapTap）',
}

# 用户提供的名单中有 2 款经多路检索未找到可靠信息，不入库，供人工核对：
#   星际酒馆（AI 情感陪伴向）——检索到的同名产品均非 AI 游戏（IPLAYGAME 文字剧情手游、
#     星际争霸2 UGC 自走棋地图）；最接近的是 Astrals（astrals.io，自称星际酒馆经营+AI 剧情），
#     但产品名不一致，无法确认
#   有友（I have a friend）——TapTap/Steam/机核/行业盘点均无结果；近似项均不相关

# 模块加载时把平台与链接映射注入每条记录，供 CSV 与看板共用
for _r in ROWS:
    _r['platform'] = PLATFORM.get(_r['game'], '待核实')
    _r['links'] = ' '.join(LINKS.get(_r['game'], []))

if __name__ == '__main__':
    with open('taptap_ai_games_visit_list.csv', 'w', encoding='utf-8-sig', newline='') as fp:
        w = csv.writer(fp)
        w.writerow([label for _, label in FIELDS] + ['拜访状态', '接触人', '拜访日期', '跟进备注'])
        order = {'L1': 0, 'L2': 1, 'L3': 2}
        conf_order = {'A': 0, 'B': 1, 'C': 2}
        for r in sorted(ROWS, key=lambda x: (conf_order.get(x['conf'], 9), order.get(x['layer'], 9))):
            w.writerow([r.get(k, '') for k, _ in FIELDS] + ['未接触', '', '', ''])
        w.writerow([])
        w.writerow(['—— 以下为明确排除项 ——'])
        w.writerow(['游戏名', 'TapTap AppID', '公司', '评分', '排除理由'])
        for e in EXCLUDED:
            w.writerow([e['game'], e['app_id'], e['company'], e['score'], e['reason']])
    print('CSV written:', len(ROWS), 'rows +', len(EXCLUDED), 'excluded')
